### ISSUE TITLE
Suggestion list continues on next widget

### ISSUE THREAD

**Issue by Thiousi** [mogelbrod/kirby-copy-files#1]
![image](https://cloud.githubusercontent.com/assets/4822666/17947979/3d7649de-6a4f-11e6-8092-211e5a9adb41.png)

**Comment by mogelbrod** [comment]
I believe this is a bug within Kirby Panel, since the plugin doesn't provide any styling that could possibly interfere with the rendering. Try filing an issue over at https://github.com/getkirby/panel and reference this. Nice catch though!

I'll reopen this if it ends up being caused by this plugin specifically.
